[project]
name = "fundamentos-de-aprendizado-maquina-e-ciencia-de-dados-para-inteligencia-artificial"
version = "0.1.0"
description = "Atividades do curso de Aprendizado de Máquina e Ciência de Dados para a Inteligência Artificial"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.23.13",
    "matplotlib>=3.11.0",
    "matplotlib-venn>=1.1.2",
    "pandas>=3.0.3",
    "ruff>=0.15.20",
]

[tool.uv]
exclude-newer = "30 days"

[dependency-groups]
dev = [
    "prek>=0.4.8",
]
